### PR TITLE
#159 Fix OnSharedPreferenceChangeListener being GCed after some time

### LINKED ISSUE #159: OnSharedPreferenceChangeListener is garbage collected
Prefser uses `SharedPreferences.registerOnSharedPreferenceChangeListener()` in `Prefser.observePreferences()`. As per the documentation of [`registerOnSharedPreferenceChangeListener()`](https://developer.android.com/reference/android/content/SharedPreferences.html#registerOnSharedPreferenceChangeListener(android.content.SharedPreferences.OnSharedPreferenceChangeListener)):

> Caution: The preference manager does not currently store a strong reference to the listener. You must store a strong reference to the listener, or it will be susceptible to garbage collection. We recommend you keep a reference to the listener in the instance data of an object that will exist as long as you need the listener.

So the current implementation leads to the listener being GCed after some time which leads to changes not being propagated to observers any longer.

There already is a fix in the RxJava1.x branch. I'm currently migrating it to the RxJava2.x branch, PR incoming.

### PR DESCRIPTION
**Pull request by ubuntudroid**
Fixes #159

### CODE REVIEW

**Comment by pwittchen** [comment]
Thanks for creating this PR! I'll review it soon.

File: library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java [hunk 1]
```diff
@@ -280,21 +285,42 @@ public boolean contains(String key) {
...
+          public void cancel() {
+            preferences.unregisterOnSharedPreferenceChangeListener(onChangeListener);
+            listenerReferences.remove(onChangeListener);
+          }
+        });
       }
     });
   }
 
+  private static class OnChangeListener
```
Comment (pwittchen) [inline library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java]: This is a new class definition, so I'd move it to the end of the file.

File: library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java [hunk 2]
```diff
@@ -280,21 +285,42 @@ public boolean contains(String key) {
    */
   public Observable<String> observePreferences() {
     return Observable.create(new ObservableOnSubscribe<String>() {
+
+      Collection<OnChangeListener> listenerReferences =
```
Comment (pwittchen) [inline library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java]: We can make it `final`.

**Review by pwittchen — CHANGES_REQUESTED** [review]
Thanks for your input. I have 2 small comments on your PR. Please have a look at them. 

After applying fixes, please squash your commits into one, so I can merge branch with one commit to keep the git log clean.

File: library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java (hunk 1 above)
Comment (ubuntudroid) [reply library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java]: Sure, will do that - I initially put it here because that's where it was on the Rx1 branch as well so I assumed this to be a project convention.

**Comment by ubuntudroid** [comment]
@pwittchen Here you go. 🤓

File: library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java (hunk 1 above)
Comment (pwittchen) [reply library/src/main/java/com/github/pwittchen/prefser/library/rx2/Prefser.java]: You're right. I'll make it consistent later within another task.

**Comment by pwittchen** [comment]
Merged. Update will be available in the next release.
